### ISSUE TITLE
Is there any particular reason that config.php isn't being watched by default?

### ISSUE THREAD

**Issue by ghost** [tighten/laravel-mix-jigsaw#12]
I noticed in the official blog template that config.php is manually configured to be watched.

https://github.com/tightenco/jigsaw-blog-template/blob/db8e29802658c7afc0ced617dc3bcea29da85865/webpack.mix.js#L11

I've also had to terminate the watch script after every time I edit the config. Isn't it just better to have it watched by default?

If you agree, should I make the PR here or do it in the `webpack.mix.js` of the main tightenco/jigsaw repo?

**Comment by bakerkretzmar** [comment]
Yeah adding `config.php` makes sense, feel free to PR otherwise I'll try to get to it today. Thanks!
