### ISSUE TITLE
Laravel Mix 6

### ISSUE THREAD

**Issue by willyw2k** [tighten/laravel-mix-jigsaw#20]
I found this error when im using laravel mix 6

TypeError: Cannot add property jigsawDone, object is not extensible

![image](https://user-images.githubusercontent.com/11731303/104450680-0b3dec00-55d3-11eb-800d-4b46990956cb.png)

**Comment by owenvoke** [comment]
@willyw2k, yeah we are working on this in #19. 👍🏻 Hopefully it can be merged soon.
