### ISSUE TITLE
Passing build folder to mix

### ISSUE THREAD

**Issue by mkuItra** [tighten/laravel-mix-jigsaw#23]
Hi, I've changed my build dir to './dist', but when I run to mix it's still searching for the default build directory

`mix.browserSync({
    server: 'dist',
    files: ['build_*/**'],
});`

this actually changes default folder and run server in dist directory, combining this together like:
`mix.jigsaw().browserSync({
    server: 'dist',
    files: ['build_*/**'],
});`

gives info that the server is already running, I guess .jigsaw() already create a server so I have to somehow pass new value there, can't find info on how to do this

**Comment by bakerkretzmar** [comment]
You need to update the `files` too, does this work?

```js
mix.jigsaw().browserSync({ server: 'dist', files: ['dist/**'] });
```

If that doesn't work can you please share all of the relevant Mix and Jigsaw config, and the exact error messages you're seeing? Thanks.

**Comment by mkuItra** [comment]
![image](https://user-images.githubusercontent.com/42417165/152247816-54d02586-9466-40b6-8a43-d74cac633be3.png)

**Comment by bakerkretzmar** [comment]
Looks like this isn't an issue with Jigsaw. As the error message says, you have another program using port 3000 already.

If you think this is an issue with this plugin please try `mix.jigsaw().browserSync({ server: 'dist', files: ['dist/**'] });` and tell me if that works, and please paste your Laravel Mix configuration and your Jigsaw configuration here so that we can help debug this.

**Comment by mkuItra** [comment]
this screen is output of
`mix.jigsaw().browserSync({ server: 'dist', files: ['dist/**'] })`

my mix config
```
const mix = require('laravel-mix');
require('laravel-mix-jigsaw');
mix.disableSuccessNotifications();
mix.jigsaw().browserSync({ server: 'dist', files: ['dist/**'] })
```

My jigsaw config is default, I've only changed bootstrap.php by adding this
`$events->beforeBuild(function ($jigsaw) {
    $jigsaw->setDestinationPath('dist');
});
`

**Comment by bakerkretzmar** [comment]
It doesn't look like this is an issue with Jigsaw. The error message says port 3000 is in use, so you probably have another program running that is using that port.

I don't think this will fix it but another thing you could try is instead of setting the destination path in a listener, set it in your config with:

```php
    'build' => [
        'destination' => 'dist',
    ],
```

**Comment by mkuItra** [comment]
For me its seems like mix.jigsaw create one server instance and then browserSync is trying to create second on the same port

**Comment by mkuItra** [comment]
when I run this
`mix.jigsaw().browserSync({ server: 'dist', files: ['dist/**'], port: 8000 })`

![image](https://user-images.githubusercontent.com/42417165/152376941-bd9caa6d-38b9-47eb-97ea-da56239e21fd.png)

**Comment by bakerkretzmar** [comment]
What version of `laravel-mix-jigsaw` are you using?

**Comment by mkuItra** [comment]
6.0.39

**Comment by bakerkretzmar** [comment]
Not Laravel Mix, this plugin: `laravel-mix-jigsaw`. Are you on v1 or v2?

**Comment by mkuItra** [comment]
oh sorry, 1.5.0

**Comment by mkuItra** [comment]
didn't know there is v2

**Comment by bakerkretzmar** [comment]
Okay that's probably the issue, I'd suggest you update to v2. v1 loaded browsersync itself so you didn't need to call `.browserSync()`, which is probably why it was being loaded twice.

**Comment by mkuItra** [comment]
Yes, that's solves issue, sorry for the trouble

**Comment by bakerkretzmar** [comment]
No worries, glad it's working for you now!
