### ISSUE TITLE
Copying larger image files leads to errors when using versioning

### ISSUE THREAD

**Issue by greimers** [tighten/laravel-mix-jigsaw#24]
I setup a new Jigsaw project and wanted my images to be versioned by Mix as well.
So I added a copy step to the `webpack.mix.js` as I have it in some of my Laravel projects:

```
const mix = require('laravel-mix');
require('laravel-mix-jigsaw');

mix.disableSuccessNotifications();
mix.setPublicPath('source/assets/build');

mix.copyDirectory('source/_assets/img', 'source/assets/build/img');
mix.jigsaw()
    .js('source/_assets/js/main.js', 'js')
    .css('source/_assets/css/main.css', 'css', [
        require('postcss-import'),
        require('tailwindcss'),
    ])
    .options({
        processCssUrls: false,
    })
    .version();

```

However, this leads to errors when I add image files to the img folder that are larger than a few KB. 
When I remove the `jigsaw()` step from Mix, it works fine. With `jigsaw` I get errors like this when I run `npm run dev`:

```
In helpers.php line 104:
                                                   
  Unable to locate Mix file: /img/og-preview.png.  
```

It also works fine with jigsaw when  I remove the versioning. So there seems to be some incompatibility.

I'm using:

* Jigsaw 1.3.41
* laravel-mix-jigsaw 1.5.0
* laravel-mix 6.0.43

**Comment by bakerkretzmar** [comment]
Can you update to laravel-mix-jigsaw v2 and let me know if you still have this issue?

**Comment by greimers** [comment]
Sorry for the late response.
Setting the version for laravel-mix-jigsaw to 2.0 actually breaks the build process. `npm run watch` will no longer start a server in that case.

Also I noticed 2.0 is not marked as released in GitHub. Is this production ready? If so, is there anything else I need to change to make 2.0 work?

**Comment by bakerkretzmar** [comment]
v2 is tagged and production-ready, yes. Looking at your config I don't _think_ you'd need to change anything no, what errors are you seeing now? The v2 updates were made in #21, maybe something in there will help you debug or figure out where the issue is coming from?
