### ISSUE TITLE
Passing custom options triggers an error in 'npm run'

### ISSUE THREAD

**Issue by zigi05** [tighten/laravel-mix-jigsaw#6]
When I pass an object containing custom options to the plugin, like so:
```js
mix.jigsaw({ browserSync: false })
   .js(...)
   .sass(...)
   .options({...})
   .version();
```
I get the following error when I run `npm run dev/watch`:

> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
>  - configuration.plugins[8] should be one of these:
>    object { apply, … } | function
>    -> Plugin of type object or instanceof Function
>    Details:
>     * configuration.plugins[8] should be an object.
>       -> Plugin instance
>     * configuration.plugins[8] should be an instance of function
>       -> Function acting as plugin

**Comment by bakerkretzmar** [comment]
Looks like Webpack doesn't like us conditionally loading plugins with `this.config.browserSync ? this.browserSyncPlugin() : null` anymore. I'll take a look this week. Thanks!
