### ISSUE TITLE
How to configure browsersync options like "open: false" and "online: false"?

### ISSUE THREAD

**Issue by ghost** [tighten/laravel-mix-jigsaw#9]
I'm using Jigsaw together with Laradock.

When I run the `watch` script without touching Jigsaw's `webpack.mix.js` everything works.

I tried using `mix.browserSync` and I get an error saying port 3000 is already in use.

I tried putting those two options in `mix.jigsaw()` but they're being ignored.

I don't know where to put the browsersync options so they'd affect the already existing instance created by Jigsaw.

Issue I made in the Jigsaw repo with screen captures: tightenco/jigsaw#464

**Comment by bakerkretzmar** [comment]
For the port, try `yarn watch --port 4000`. I don't think it's possible to configure the `open` and `online` options right now, we should probably add that.

**Comment by ghost** [comment]
Ok thanks, the `online` option is actually something I need because at the moment my connection isn't always stable and having that option turned on just stalls browsersync and slows down my workflow.

**Comment by ghost** [comment]
After staring at `index.js` for about an hour,  I think I finally understand how this file works.

If I don't make a pull request within the next 8 hours, it probably means I was wrong and couldn't fix it. (on my phone, couldn't test it right now)
